### ISSUE TITLE
Не разблокировывается кнопка "Рассчитать" при заполнении все параметров

### ISSUE THREAD

**Issue by R1kse** [greatstudentkaze/js-calories-counter#1]
Не разблокировывается кнопка "Рассчитать" при заполнении все параметров, в консоли браузера выводит ошибку "Uncaught SyntaxError: Cannot use import statement outside a module"

**Comment by greatstudentkaze** [comment]
Привет! Подскажи, пожалуйста, в каком браузере (и версии) так происходит?

**Comment by R1kse** [comment]
Google Chrome 
Версия 96.0.4664.110

**Comment by greatstudentkaze** [comment]
Хм, странно...
Не возникает такой проблемы ни в хроме, ни в других браузерах 
https://greatstudentkaze.github.io/js-calories-counter/

**Comment by R1kse** [comment]
я просто пытался изменить стиль интерфейса но программную часть не трогал, вот сайт http://koorsachenko.ga/ (это мой курсач):D

**Comment by R1kse** [comment]
Менюшка так расположена ибо я хочу адаптировать под телефон и буду запускать через Webview на платформе Android Studio

**Comment by R1kse** [comment]
Попробуйте скачать свой код с гитхаба и его запустить мб у вас тоже ошибку выдаст

**Comment by greatstudentkaze** [comment]
понятно

тебе нужно вот этот скрипт использовать:
https://github.com/greatstudentkaze/js-calories-counter/blob/gh-pages/js.00a46daa.js

на гитхабе лежат исходники – несобранный js-bundle
